# Generated by Django 4.2.16 on 2024-11-16 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifteg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('store_name', models.CharField(max_length=100)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(default='Not specified', max_length=100)),
                ('product_description', models.TextField(default='No description provided')),
                ('identity_image', models.ImageField(default='default.jpg', upload_to='identity/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='thrifteg.seller')),
            ],
        ),
    ]
