# Generated by Django 5.1.2 on 2024-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifteg', '0006_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
