# Generated by Django 4.2.16 on 2024-12-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifteg', '0006_item_num_ratings_item_rating_seller_num_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thrifteg.seller'),
        ),
    ]
